// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using obras_service.Repositories;

namespace obras_service.Migrations
{
    [DbContext(typeof(ContextDatabase))]
    [Migration("20221208044527_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("obras_service.Models.Obras", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("EstadoSolicitud")
                        .HasColumnType("text");

                    b.Property<string>("FechaSolicitud")
                        .HasColumnType("text");

                    b.Property<int>("IdSolicitudAlmacen")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("IdSolicitud");

                    b.ToTable("Obras");
                });
#pragma warning restore 612, 618
        }
    }
}
